rm -f CMakeCache.txt;
rm -rf CMakeFiles

TCHEM_INSTALL_PATH=/your/tchem/install/path
TCHEM_SRC_PATH=/your/tchem/src/path
KOKKOS_INSTALL_PATH=/your/kokkos/install/path
KOKKOS_NVCC_WRAPPER=${KOKKOS_INSTALL_PATH}/bin/nvcc_wrapper

cmake \
    -D CMAKE_INSTALL_PREFIX=${TCHEM_INSTALL_PATH} \
    -D CMAKE_CXX_COMPILER=${KOKKOS_NVCC_WRAPPER} \
    -D CMAKE_CXX_FLAGS="-g -lineinfo" \
    -D TCHEM_ENABLE_KOKKOS=ON \
    -D KOKKOS_INSTALL_PATH=${KOKKOS_INSTALL_PATH} \
    -D TCHEM_ENABLE_KOKKOSKERNELS=ON \
    -D KOKKOSKERNELS_INSTALL_PATH=${KOKKOSKERNELS_INSTALL_PATH} \
    ${TCHEM_SRC_PATH}
