IF (NOT LAPACKE_FOUND)
  # Check LAPACKE installation
  FIND_PATH(LAPACKE_FOUND_INCLUDE_PATH lapacke.h HINTS ${LAPACKE_INSTALL_PATH}/include)
  FIND_LIBRARY(LAPACKE_FOUND_LIBRARY NAMES lapacke HINTS ${LAPACKE_INSTALL_PATH}/lib ${LAPACKE_INSTALL_PATH}/lib64)

  IF (LAPACKE_FOUND_INCLUDE_PATH AND LAPACKE_FOUND_LIBRARY)
    ADD_LIBRARY(lapacke UNKNOWN IMPORTED)
    SET_TARGET_PROPERTIES(lapacke PROPERTIES 
      IMPORTED_LOCATION ${LAPACKE_FOUND_LIBRARY}
      INTERFACE_INCLUDE_DIRECTORIES ${LAPACKE_FOUND_INCLUDE_PATH}
      INTERFACE_COMPILE_OPTIONS "-I${LAPACKE_FOUND_INCLUDE_PATH}")    
    SET(LAPACKE_FOUND ON)    
    MESSAGE("-- LAPACKE is found at ${LAPACKE_FOUND_LIBRARY})
  ELSE()
    MESSAGE(FATAL_ERROR "-- LAPACKE is not found at ${LAPACKE_INSTALL_PATH}")
  ENDIF()
ENDIF()