# Check Kokkos installation
FILE(GLOB_RECURSE KOKKOSKERNELS_FOUND_CMAKE_FILE "${KOKKOSKERNELS_INSTALL_PATH}/KokkosKernelsConfig.cmake")

MESSAGE(STATUS "KokkosKernels install path : ${KOKKOSKERNELS_INSTALL_PATH}")
MESSAGE(STATUS "KokkosKernels found cmake config : ${KOKKOSKERNELS_FOUND_CMAKE_FILE}")

IF (KOKKOSKERNELS_FOUND_CMAKE_FILE) # AND KOKKOSKERNELS_FOUND_INCLUDE_PATH AND KOKKOSKERNELS_FOUND_LIBRARY)
  INCLUDE(${KOKKOSKERNELS_FOUND_CMAKE_FILE})
  SET(KOKKOSKERNELS_FOUND ON)
ELSE()
  MESSAGE(FATAL_ERROR "-- KokkosKernels is not found at ${KOKKOSKERNELS_INSTALL_PATH}")
ENDIF()
