# Check Kokkos installation
FILE(GLOB_RECURSE KOKKOS_FOUND_CMAKE_FILE "${KOKKOS_INSTALL_PATH}/KokkosConfig.cmake")

MESSAGE(STATUS "Kokkos install path : ${KOKKOS_INSTALL_PATH}")
MESSAGE(STATUS "Kokkos found cmake config : ${KOKKOS_FOUND_CMAKE_FILE}")

IF (KOKKOS_FOUND_CMAKE_FILE) # AND KOKKOS_FOUND_INCLUDE_PATH AND KOKKOS_FOUND_LIBRARY)
  INCLUDE(${KOKKOS_FOUND_CMAKE_FILE})
  SET(KOKKOS_FOUND ON)
ELSE()
  MESSAGE(FATAL_ERROR "-- Kokkos is not found at ${KOKKOS_INSTALL_PATH}")
ENDIF()