# Check yaml installation
FILE(GLOB_RECURSE YAML_FOUND_CMAKE_FILE "${YAML_INSTALL_PATH}/yaml-cpp-config.cmake")

MESSAGE(STATUS "YAML install path : ${YAML_INSTALL_PATH}")
MESSAGE(STATUS "YAML found cmake config : ${YAML_FOUND_CMAKE_FILE}")

IF (YAML_FOUND_CMAKE_FILE)
  INCLUDE(${YAML_FOUND_CMAKE_FILE})
  SET(YAML_FOUND ON)
ELSE()
  MESSAGE(FATAL_ERROR "-- YAML is not found at ${YAML_INSTALL_PATH}")
ENDIF()
